DROP TABLE IF EXISTS participations CASCADE;

CREATE TABLE participations (
  id SERIAL PRIMARY KEY NOT NULL,
  vote BOOLEAN
  time_id INTEGER NOT NULL REFERENCES times(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
);
