DROP TABLE IF EXISTS votes CASCADE;

CREATE TABLE votes (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  event_id INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  calendar_date VARCHAR(255) NOT NULL,
  timeslot VARCHAR(5) NOT NULL
);
